#!/usr/bin/env node  
const asciify = require('asciify');

//  AUTOLOAD LIBRARY nodefony NODE
const autoloader = require("./vendors/nodefony/core/autoloader");
autoloader.load("./app/appKernel.js");
autoloader.load("./vendors/nodefony/console/console.js");

// START CONSOLE
asciify("      NODEFONY", {font:'standard'}, function(err, res){

	console.log('\033[31m'+res+'\033[0m');
	
	process.env["MODE_START"] = "NODEFONY_CONSOLE" ;

	var kernel = new nodefony.console( "prod", false, autoloader,{
		node_start:process.env["MODE_START"]
	});
	autoloader.setKernel( kernel );
});

