#!/usr/bin/env node
const asciify = require('asciify');
const path = require("path");

var autoloader = null ;
// AUTOLOADER
try {
	autoloader = require("nodefony");
}catch(e){
	autoloader = require(".", "src", "nodefony", "core", "autoloader");	
}
autoloader.load( path.resolve(".", "app", "appKernel.js" ) );
autoloader.load( path.resolve( autoloader.dirname, "console", "console.js") );

// START CONSOLE
asciify("      NODEFONY", {font:'standard'}, function(err, res){

	console.log('\033[31m'+res+'\033[0m');
	
	process.env["MODE_START"] = "NODEFONY_CONSOLE" ;

	var kernel = new nodefony.console( "prod", false, autoloader,{
		node_start:process.env["MODE_START"]
	});
	autoloader.setKernel( kernel );
});
