#!/usr/local/bin/node

var asciify = require('asciify');

//  AUTOLOAD LIBRARY nodefony NODE
var autoloader = require("./vendors/nodefony/core/autoloader");
autoloader.load("./app/appKernel.js");


asciify("      NODEFONY", {font:'standard'}, function(err, res){
		console.log('\033[31m'+res+'\033[0m'); 
	//var kernel =new nodefony.appKernel("SERVER","prod", false, autoloader);
	var kernel =new nodefony.appKernel("SERVER", "dev", true, autoloader);
});

