#!/usr/bin/env node --no-warnings --no-deprecation

var cluster = require('cluster');	


// AUTOLOADER 
var autoloader = require("./vendors/nodefony/core/autoloader");
autoloader.load("./app/appKernel.js");

/*
 *
 * NODEFONY FRAMEWORK START WITH PM2
 *
 *	PRODUCTION / DEVELOPEMENT
 *
 */
if ( process.env["MODE_START"] && process.env["MODE_START"] === "PM2"){

	return new nodefony.appKernel("SERVER", "prod", false, autoloader,{
		node_start:process.env["MODE_START"]
	});
}


/*
 *
 * NODEFONY FRAMEWORK START 
 *
 *	PRODUCTION
 *
 */
if (cluster.isMaster) {
	
	require('asciify')("      NODEFONY", {font:'standard'}, function(err, res){
		console.log('\033[31m'+res+'\033[0m');
	});

	var nbProc = require('os').cpus().length; 
	//var nbProc = 1; 
	for (var i=0 ; i<nbProc;i++){
		cluster.fork();
	}

	cluster.on('disconnect', function(worker) {
		console.error('disconnect!');
	});

}else {
	return new nodefony.appKernel("SERVER", "prod", false, autoloader,{
		node_start:process.env["MODE_START"]	
	});
}








