#!/usr/bin/env node

// --expose-gc --trace-gc --log-gc --trace-gc-verbose
//--debug


/*var profiler = require('v8-profiler');
var heapdump = require('heapdump');
heapdump.writeSnapshot(process.cwd()+'/tmp/' + Date.now() + '.heapsnapshot', function(err, filename) {
	console.log('heapdump written to', filename);
});*/

/*
 *
 * NODEFONY FRAMEWORK  
 *
 *	DEVELOPPEMENT
 *
 */
// AUTOLOADER
const autoloader = require("./vendors/nodefony/core/autoloader");
autoloader.setEnv("dev");
autoloader.load("./app/appKernel.js");

process.env["MODE_START"] = "NODEFONY_DEV" ;

require('asciify')("      NODEFONY", {font:'standard'}, function(err, res){
	console.log('\033[31m'+res+'\033[0m'); 
	// KERNEL 
	var kernel = new nodefony.appKernel("SERVER", "dev", true, autoloader, {
		node_start:process.env["MODE_START"]
	});
	autoloader.setKernel(kernel);
	return kernel ;
});
