

# INSTALL NodeJs dependencies

install:
	# nodemailer (mailer for nodejs)
	npm install nodemailer@* --save ../../../../../ ;

	# juice (css in file to inline css)
	npm install juice@* --save ../../../../../ ;